---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - autoscaling.brian.io
  resources:
  - predictivehpas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.brian.io
  resources:
  - predictivehpas/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.brian.io
  resources:
  - predictivehpas/status
  verbs:
  - get
  - patch
  - update
